export const BatStateUColors = {
  maroon:         '#8B0000',
  maroonDark:     '#6B0000',
  maroonMid:      '#A31621',
  maroonLight:    '#FDECEA',
  maroonSurface:  '#FFF5F5',

  forest:         '#1A5C38',
  forestDark:     '#144D2E',
  forestMid:      '#1E7A47',
  forestLight:    '#DCFCE7',
  forestSurface:  '#F0FDF4',
  forestBorder:   '#BBF7D0',

  white:          '#FFFFFF',
  surface:        '#F7F7F8',
  surfaceAlt:     '#F0F0F2',
  border:         '#E5E5E7',
  textPrimary:    '#1A1A1A',
  textSecondary:  '#6B6B6B',
  textMuted:      '#9A9A9A',

  verified:       '#16A34A',
  verifiedBg:     '#DCFCE7',
  error:          '#DC2626',
  errorBg:        '#FEE2E2',
  warning:        '#D97706',
  warningBg:      '#FEF3C7',
};

export const StudentTheme = {
  primary:        BatStateUColors.maroon,
  primaryDark:    BatStateUColors.maroonDark,
  primaryLight:   BatStateUColors.maroonLight,
  surfaceBg:      BatStateUColors.maroonSurface,
  tabActive:      BatStateUColors.maroon,
  tabBar:         '#FFFFFF',
  tabBarBorder:   '#E5E5E7',
  headerBg:       '#FFFFFF',
  avatarBg:       BatStateUColors.maroonLight,
  avatarText:     BatStateUColors.maroonDark,
  ctaBg:          BatStateUColors.maroon,
  ctaText:        '#FFFFFF',
  linkColor:      BatStateUColors.maroon,
  chipSelected:   BatStateUColors.maroon,
  chipText:       '#FFFFFF',
};

export const FreelancerTheme = {
  primary:        BatStateUColors.forest,
  primaryDark:    BatStateUColors.forestDark,
  primaryLight:   BatStateUColors.forestLight,
  surfaceBg:      BatStateUColors.forestSurface,
  tabActive:      BatStateUColors.forest,
  tabBar:         '#FFFFFF',
  tabBarBorder:   '#E5E5E7',
  headerBg:       '#FFFFFF',
  avatarBg:       BatStateUColors.forestLight,
  avatarText:     BatStateUColors.forestDark,
  ctaBg:          BatStateUColors.forest,
  ctaText:        '#FFFFFF',
  linkColor:      BatStateUColors.forest,
  chipSelected:   BatStateUColors.forest,
  chipText:       '#FFFFFF',
};

// Keep full compatibility for files statically importing 'Colors'
export const Colors = {
  primary:        BatStateUColors.maroonMid,
  primaryDark:    BatStateUColors.maroonDark,
  primaryLight:   BatStateUColors.maroonLight,
  background:     BatStateUColors.white,
  surface:        BatStateUColors.surface,
  surfaceAlt:     BatStateUColors.surfaceAlt,
  border:         BatStateUColors.border,
  textPrimary:    BatStateUColors.textPrimary,
  textSecondary:  BatStateUColors.textSecondary,
  textMuted:      BatStateUColors.textMuted,
  verified:       BatStateUColors.verified,
  verifiedBg:     BatStateUColors.verifiedBg,
  forest:         BatStateUColors.forest,
  forestBg:       BatStateUColors.forestLight,
  white:          BatStateUColors.white,
  error:          BatStateUColors.error,
  errorBg:        BatStateUColors.errorBg,
};

